### ISSUE TITLE
Auto start MavensMate-app

### ISSUE THREAD

**Issue by sturev** [joeferraro/MavensMate-app#30]
This doesn't appear to be working. In the User Plugin Settings I have this "mm_start_mavensmate_app" : true, but still get this error when opening Sublime: [ERROR]: Could not contact local MavensMate server, please ensure MavensMate-app is installed and running...

I've confirmed the paths are set correctly in the settings and everything works great if I manually start the app prior to opening Sublime.

Win10, v0.0.6

**Comment by sturev** [comment]
Hold on this, it appears that the settings (Sublime\MM\Settings\User Plugin...) are not the same as MavensMate-app\Settings... I'm updating those and will see if things change.

**Comment by Katulka** [comment]
I've got the same error, win10, 0.0.7-beta4

Path is correct in settings.

**Comment by coolbulevar** [comment]
+1 for this.

**Comment by LKozakewycz** [comment]
+1 as well. Was just about to post this!

**Comment by archita6** [comment]
I have got the same error 
Windows 7 x64, v0.0.7

**Comment by joeferraro** [comment]
sorry guys, was an issue with the windows command that was locking sublime text up, this should be resolved in v5.0.2. please ensure `mm_start_mavensmate_app` is `true` and your `mm_mavensmate_app_location` location is valid

**Comment by sturev** [comment]
v5.0.4 and I still have the issue...  paths are correct in both the app and user settings and mm_start_mavensmate_app is true.

**Comment by LKozakewycz** [comment]
Me too - this issue still exists.

**Comment by Shababsoft** [comment]
@joeferraro I have same issue with the latest version (v7)
